# Site settings
title: The Coffee Workshop
email: brice.dutheil@gmail.com
description: "Java, docker, zookeeper, mockito, engineering, ..."


baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.arkey.fr" # the base hostname & protocol for your site
#enforce_ssl: "blog.arkey.fr"
cname: "https://blog.arkey.fr"
twitter_username: BriceDutheil
github_username: bric3
linkedin_link: https://fr.linkedin.com/in/dutheilbrice
stackoverflow_link: http://stackoverflow.com/users/48136/brice
speakerdeck_username: bric3

title_image: "https://s.gravatar.com/avatar/f31c7fbcbb0766d0632d96fd7e74b649?s=500&d=mm"
#google_analytics: "UA-20365477-4"
disqus_account: thecoffeeworkshop
github_repository: https://github.com/bric3/blog
#post_limit: 5

locale: fr

# Build settings
markdown: kramdown
highlighter: rouge

kramdown:
    input: GFM
    syntax_highlighter: rouge
    # parse_block_html: true
    # syntax_highlighter_opts:
    #     line_numbers: true

permalink: /:year/:month/:day/:title/

#exclude: [vendor]
exclude:
  - 'tmp'


gems:
  - jekyll-gist
  - jekyll-redirect-from
  - jemoji
  - jekyll-sitemap
  - jekyll-feed
whitelist:
  - jekyll-gist
  - jekyll-redirect-from
  - jemoji
  - jekyll-sitemap
  - jekyll-feed
