# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Brice Dutheil
email: brice.dutheil@gmail.com

#write html inside the double quotes to display in jumbotron
description: "<h1>The Coffee Workshop</h1><h3>Don't waste your time!</h3>"



baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://bric3.github.io/blog/" # the base hostname & protocol for your site
twitter_username: BriceDutheil
github_username:  bric3

# Build settings
markdown: kramdown

exclude:
  - 'tmp'
