# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Coffee Workshop
email: brice.dutheil@gmail.com
description: "Hmmm, engineering..."


baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://bric3.github.io/blog/" # the base hostname & protocol for your site
twitter_username: BriceDutheil
github_username: bric3
linkedin_link: https://fr.linkedin.com/in/dutheilbrice
stackoverflow_link: http://stackoverflow.com/users/48136/brice
speakerdeck_username: bric3

title_description: "About software engineering... <em>mostly around Java</em><br>by Brice Dutheil"
title_image: "https://s.gravatar.com/avatar/f31c7fbcbb0766d0632d96fd7e74b649?s=500&d=mm"
#google_analytics: "UA-20365477-4"
#disqus_account: cartenoire
github_repository: https://github.com/bric3/blog
#post_limit: 5

# Footer
footer_left: "<i class=\"fa fa-cogs\"></i> <a href=\"https://twitter.com/BriceDutheil\">Brice Dutheil</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/bric3/blog\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"


# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  # parse_block_html: true

permalink: /:year/:month/:day/:title/

#exclude: [vendor]
exclude:
  - 'tmp'
