# https://gohugo.io/getting-started/configuration/

baseURL = "https://blog.arkey.fr"

title = "The Coffee Workshop"
# copyright = "Brice Dutheil — All rights reserved."

theme = "hyde-hyde"

# generate robots.txt
enableRobotsTXT = true

# disqusShortname = "your-disqus-shortname"
# googleAnalytics = "your-google-analytics-id"

languageCode = "en"

# Content without language indicator will default to this language.
defaultContentLanguage = "en-us"

summarylength = 50

canonifyURLs = false
preserveTaxonomyNames = true

# Remove accents from URL, otherwise they appear as url-encoded
removePathAccents = true

# Configure pagination
paginate = 22
paginatePath = "page"


# Render the default content language in subdir, e.g. content/en/. 
# The site root / will then redirect to /en/.
# defaultContentLanguageInSubdir = false

# Enable Emoji emoticons support for page content
# See https://www.webpagefx.com/tools/emoji-cheat-sheet/
enableEmoji = true


# [markup]
#     [markup.goldmark]                   # This is the markdown rendered
#         [markup.goldmark.renderer]
#             unsafe = true               # Allow html (needed for some shortcodes)

#     [markup.highlight]
#         codeFences = true               # Enable highlighting inside codefences
#         guessSyntax = false             # Highlight code without language tag
#         hl_Lines = ""
#         lineNoStart = 1
#         lineNos = false
#         lineNumbersInTable = true
#         noClasses = true                # Use the theme's style sheet
#         style = "monokai"
#         tabWidth = 4


# for use in templates
## Site Settings
[params]
    author = "Brice Dutheil"
    title = "Arkey"
    # description = "..."
    authorimage = "/img/hugo.png"

    # Site description
    description = "Java mostly, other stuff sometimes"

    # Favicon file (relative to baseURL - place below static or assets folder)
    # favicon = "favicon.png"
    # Custom css file (relative to baseURL - place below static or assets folder)
    # css = "custom.css"

    # Define formatting of dates
    # (optional, falls back to RFC822 format if not set)
    # For reference to date and time formatting, see:
    # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
    # Make sure to set showMetaDates to true to see any dates
    dateformat = "2006-01-02"

    # sidebar, copyright & license
    copyright = "Brice Dutheil"
    since = 2010
    license = "DevJournal"
    licenseURL = "https://github.com/hemangsk/DevJournal"
    showBuiltWith = true

    # https://highlightjs.org
    highlightjs = true
    highlightjsstyle = "github"

    # Table of contents
    #toc = none, "hugo", or "tocbot"

    mainSections = ["posts"]

## Social Accounts
[params.social]
    github = "bric3"
    linkedin = "dutheilbrice"
    twitter = "@BriceDutheil"
    stackoverflow = "48136/brice"
    # email = "your-email@example.com"
    gravatar = "brice.dutheil@gmail.com"

[permalinks]
    posts = "/:year/:month/:day/:title/"

# Define all supported taxonomies (add series to the default)
[taxonomies]
    tags = "tags"
    categories = "categories"
    series = "series"


[author]
    name = "Brice Dutheil"
    email = "brice.dutheil@gmail.com"


[services.rss]
    # limit the length of the rss feed (default: unlimited)
    limit = 0


[menu]
    [[menu.main]]
        # name = "Home"
        pre = "<i class='fa fa-home'></i> <code>cd ~</code>"
        url = "/"
        weight = -100

    # Configure main menu entries (header)
    # Currently set to list all taxonomies and posts
    [[menu.main]]
        identifier = "post"
        # name = "Posts"
        title = "All posts"
        pre = "<i class='fa fa-stream'></i> <code>ls posts/*</code>"
        # pre = "<i class='fa fa-blog'></i> <code>ls posts/*</code>"
        # pre = "<i class='far fa-newspaper'></i> <code>ls posts/*</code>"
        url = "/posts/"
        weight = 1

    # [[menu.main]]
    #     identifier = "categories"
    #     name = "Categories"
    #     title = "All categories"
    #     url = "/categories/"
    #     weight = 2

    [[menu.main]]
        identifier = "series"
        # name = "Series"
        pre = "<i class='fa fa-list-alt'></i> <code>grep -o posts/* series | sort | uniq</code>"
        # pre = "<i class='fa fa-object-group'></i> <code>grep posts/* series | sort | uniq</code>"
        title = "All series"
        url = "/series/"
        weight = 2

    [[menu.main]]
        identifier = "tags"
        # name = "Tags"
        pre = "<i class='fa fa-tags'></i> <code>grep -o posts/* tags | sort | uniq</code>"
        title = "All tags"
        url = "/tags/"
        weight = 3

    [[menu.main]]
        identifier = "whoami"
        # name = "Who Am I ?"
        pre = "<i class='fa fa-id-card'></i> <code>whoami</code>"
        title = "About me"
        weight = 4
        url = "/whoami/"

    [[menu.main]]
        identifier = "coolstuff"
        # name = "Cool stuff"
        pre = "<i class='fa fa-map-pin'></i> <code>cd cool-stuff</code>"
        title = "Cool stuff"
        weight = 4
        url = "/cool-stuff/"

    # Define the entries for post metadata
    # Identifiers should match with the taxonomy entries
    [[menu.meta]]
        identifier = "categories"
        name = "Categories"
        weight = 1
    [[menu.meta]]
        identifier = "series"
        name = "Series"
        weight = 2
    [[menu.meta]]
        identifier = "tags"
        name = "Tags"
        weight = 3


    # Add some footer links to your likings
    [[menu.footer]]
        name = "GitHub"
        title = "Theme repository"
        url = "https://github.com/bric3/bric3.github.io"
        weight = 1

    [[menu.footer]]
        name = "Slick"
        title = "Theme page on gohugo.io"
        url = "https://themes.gohugo.io/slick"
        weight = 2

    [[menu.footer]]
        name = "Toor"
        title = "Some website, using this theme"
        url = "https://www.toor.su"
        weight = 3


# [params.search]
# client = "fuse" # algolia / fuse / lunr

# [languages]
# # edit this block for your own language
# [languages.en]
# lang = "en"
# languageName = "English"
# weight = 1

# [languages.fr]
# lang = "fr"
# languageName = "French"
# weight = 1
